name: Test CI/CD pipeline
on:
  push:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "testing..."

  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - run: echo "building..."

  staging:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - run: echo "deploy to staging..."
      - name: Set develop image tag variable
        run: |
          if [ ${{ github.ref_name }} == 'main' ]; then
            export IMAGE_TAG=develop
          fi
        shell: bash
      - run: echo $IMAGE_TAG
      - name: Set develop image tag variable
        run: |
          if [ ${{ github.ref_name }} != 'main' ]; then
            export IMAGE_TAG=rtbtrbtrbrtb
          fi
        shell: bash
      - run: echo $IMAGE_TAG
      - run: echo "deploy to production..."

  production:
    needs: staging
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: ptgladk
          minimum-approvals: 1
      - run: echo "deploy to production..."
